################################################
# Crop Checker configuration file              #
#                                              #
# Use any hoe to check growth progress of      #
# crops, or the honey level of bee hives.      #
# A specific tool can set in place of a hoe,   #
# by enabling the override tool, and setting   #
# the item. Set to AIR to use an empty hand.   #
# Author: steve4744                            #
################################################
# Check for new version
Check_For_Update: true
# Number of seconds to display growth status (max 8)
display_time: 3
# Enable the preferred method(s) to display the block info
Display:
  scoreboard:
    enabled: true
  actionbar:
    enabled: false
    textcolor: WHITE
  bossbar:
    enabled: false
    barcolor: GREEN
    textcolor: WHITE
# Set a specific item to use instead of a hoe.
override_tool:
  enabled: false
  item: IRON_HOE