############################################## #
# Crop Checker configuration file               #
#                                               #
# Use any hoe to check the growth progress of   #
# crops, or the honey level of bee hives.       #
# A specific tool can be set in place of a hoe  #
# by enabling the override tool and setting     #
# the item.                                     #
# Author: steve4744                             #
############################################## #

# Check for new version.
Check_For_Update: true
#
# Number of seconds to display growth status (max 8).
display_time: 3
#
# Enable the preferred method(s) to display the crop info.
Display:
  scoreboard:
    enabled: true
  actionbar:
    enabled: false
    # text colour supports hex/rgb colour codes, default is WHITE
    #textcolor: <#ff00e0>
    #textcolor: '&b'
    textcolor: WHITE
  bossbar:
    enabled: false
    barcolor: GREEN
    textcolor: WHITE
#
# Set a specific item to use instead of a hoe. Set the
# item to AIR to use an empty hand.
override_tool:
  enabled: false
  item: IRON_HOE
#
# Set how the player selects the crop/item.
click_type:
  right_click: true
  shift_click: false
