name: CropChecker
main: io.github.steve4744.cropchecker.CropChecker
author: steve4744
version: 3.2
api-version: 1.17
description: Checks the age of your crops
softdepend: [ItemsAdder]
commands:
  cropchecker:
    description: CropChecker commands
permissions:
  cropchecker.use:
    description: used to control who can use CropChecker and where.
    default: true
  cropchecker.admin:
    description: permission to reload config
    default: op